name: CI Push to Dockerhub on release

on:
 release:
  types: published

jobs:
  main:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
       name: Get the tag name
       run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      -
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
      -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
       name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
        push: true
        tags: singlecellacademy/scap:${{ env.TAG }}
